name: "release-tracker-workflow"

on:
  push:
    branches:
      - main

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn clean test
  test-integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3-bookworm
        env:
          POSTGRES_USER: "release-tracker"
          POSTGRES_DB: "release_tracker"
          POSTGRES_PASSWORD: "dev"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Init PostgreSQL
        env:
          POSTGRES_USER: "release-tracker"
          POSTGRES_DB: "release_tracker"
          POSTGRES_PASSWORD: "dev"
        run: |
          pgsql -f local/mnt/init/db_init.sql
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn clean test -Dtest.condition.pgsql=true
  package:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'maven'
    - name: Maven Package
      run: mvn clean package
